{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mcexport.fullname" . }}
  labels:
    {{- include "mcexport.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "mcexport.selectorLabels" . | nindent 6 }}
{{- end }}
